name: clash-of-clans
dependencies:
  - python=3.10.6
  - numpy=1.23.3
  - pandas=1.4.4
  - requests=2.28.1
  - pip=22.2.2
  - pip:
    - coc-py==2.2.3
    - asyncio==3.4.3
    - pyyaml==6.0
    - azure-data-tables==12.4.1