TroopSettings:
  TableName: "TroopTest"
  Categories: ["hero", "pet", "troop", "spell"]
  ScrapeEnabled: true
  NullIdScrapeEnabled: false

GoldPassSettings:
  TableName: "GoldPassTest"
  ScrapeEnabled: true

PlayerSettings:
  TableName: "player_test"
  ScrapeEnabled: true
  # Player data to be scraped.
  #   wantosleep: #Y9VG28UL
  #   wantosleep2: #LG8U8UC99
  #   zWyeBroken: #YG2V9YPUP
  #   zoecmy: #QPPLYYJGY
  Players: ["#Y9VG28UL", "#LG8U8UC99", "#YG2V9YPUP", "#QPPLYYJGY"]

ClanSettings:
  TableName: "clan"
  ScrapeEnabled: true
  Clans: []
  ScrapeAllMembersEnabled: true