StorageHandlerSettings:
  UpsertAtFailedPushEnabled: true

TroopSettings:
  TableName: "Troop"
  Categories: ["hero", "pet", "home_troop", "super_troop", "builder_troop", "spell"]
  ScrapeEnabled: true
  NullIdScrapeEnabled: false

GoldPassSettings:
  TableName: "GoldPass"
  ScrapeEnabled: true

PlayerSettings:
  TableName: "Player"
  ScrapeEnabled: true
  # Player data to be scraped.
  #   zoecmy: #QPPLYYJGY
  Players: ["#QPPLYYJGY"]

ClanSettings:
  TableName: "Clan"
  ScrapeEnabled: true
  # Clan data to be scraped.
  #   ATAS: #9J82VUV
  #     includes:
  #       - #Y9VG28UL: wantosleep
  #       - #LG8U8UC99: wantosleep2
  #   Syrius: #2RQ2VR89
  #     includes:
  #       - #YG2V9YPUP: zWyeBroken
  Clans: ["#9J82VUV", "#2RQ2VR89"]
  MemberScrapeEnabled: true

LocationSettings:
  TableName: "Location"
  ScrapeEnabled: true
  # Location data to be scraped.
  #   1: 32000144
  #   2: 32000209
  Locations: [32000144, 32000209]
  ClanScrapeByLocationEnabled: true
  ClanScrapeLimit: 10
  PlayerScrapeByLocationEnabled: false
  PlayerScrapeLimit: 1