TroopSettings:
  TableName: "troop_test"
  Troop: ["heroes", "pets", "troops", "spells"]
  ScrapeEnabled: true
  ScrapeFrequency: "1 month"

GoldPassSettings:
  TableName: "GoldPassTest"
  ScrapeEnabled: true
  ScrapeFrequency: "1 month"
  PartitionKey: "SeasonId"
  RowKey: "TimeStamp"

PlayerSettings:
  TableName: "player_test"
  ScrapeEnabled: true
  ScrapeFrequency: "1 day"
  # Player data to be scraped.
  #   wantosleep: #Y9VG28UL
  #   wantosleep2: #LG8U8UC99
  #   zWyeBroken: #YG2V9YPUP
  #   zoecmy: #QPPLYYJGY
  Players: ["#Y9VG28UL", "#LG8U8UC99", "#YG2V9YPUP", "#QPPLYYJGY"]

ClanSettings:
  TableName: "clan"
  ScrapeEnabled: true
  ScrapeFrequency: "1 day"
  Clans: []
  ScrapeAllMembersEnabled: true