StorageHandlerSettings:
  UpsertAtFailedPushEnabled: false

TroopSettings:
  TableName: "Troop"
  Categories: ["hero", "pet", "troop", "spell"]
  ScrapeEnabled: true
  NullIdScrapeEnabled: false

GoldPassSettings:
  TableName: "GoldPass"
  ScrapeEnabled: true

PlayerSettings:
  TableName: "Player"
  ScrapeEnabled: true
  # Player data to be scraped.
  #   wantosleep: #Y9VG28UL
  #   wantosleep2: #LG8U8UC99
  #   zWyeBroken: #YG2V9YPUP
  #   zoecmy: #QPPLYYJGY
  Players: ["#Y9VG28UL", "#LG8U8UC99", "#YG2V9YPUP", "#QPPLYYJGY"]

ClanSettings:
  TableName: "Clan"
  ScrapeEnabled: true
  Clans: ["#9J82VUV"]
  MemberScrapeEnabled: true