CocClient:
  RestartSleepTime: 5

StorageHandlerSettings:
  RetryEntityCreationEnabled: true
  RetryEntityCreationCount: 1
  RetryEntityExtractionEnabled: true
  RetryEntityExtractionCount: 1
  UpsertAtFailedPushEnabled: true
  ThreadWorkerCount: 9

TroopSettings:
  TableName: "Troop"
  Categories: ["hero", "pet", "home_troop", "super_troop", "builder_troop", "spell"]
  ScrapeEnabled: true
  AbandonScrapeIfEntityExists: true
  NullIdScrapeEnabled: false

GoldPassSettings:
  TableName: "GoldPass"
  ScrapeEnabled: true
  AbandonScrapeIfEntityExists: true

PlayerTroopsSettings:
  TableName: "PlayerTroop"
  ScrapeEnabled: true
  AbandonScrapeIfEntityExists: true
  # Troop Id: Barbarian - 4000000
  ValidationTroopId: 4000000

PlayerSettings:
  TableName: "Player"
  ScrapeEnabled: true
  AbandonScrapeIfEntityExists: true
  # Player data to be scraped.
  #   zoecmy: #QPPLYYJGY
  Players: ["#QPPLYYJGY"]

ClanSettings:
  TableName: "Clan"
  ScrapeEnabled: true
  AbandonScrapeIfEntityExists: true
  # Clan data to be scraped.
  #   ATAS: #9J82VUV
  #     includes:
  #       - #Y9VG28UL: wantosleep
  #       - #LG8U8UC99: wantosleep2
  #   Syrius: #2RQ2VR89
  #     includes:
  #       - #YG2V9YPUP: zWyeBroken
  Clans: ["#9J82VUV", "#2RQ2VR89"]
  MemberScrapeEnabled: true

LocationSettings:
  TableName: "Location"
  ScrapeEnabled: true
  AbandonScrapeIfEntityExists: true
  # Location data to be scraped.
  #   1: 32000144 - Malaysia
  #   2: 32000209 - Singapore
  Locations: [32000144, 32000209]
  # If the following is enabled, the 'Location' setting will be ignored.
  ScrapeFromAllLocationsEnabled: true
  ClanScrapeByLocationEnabled: true
  ClanScrapeLimit: 2
  PlayerScrapeByLocationEnabled: true
  PlayerScrapeLimit: 2